name: Cypress cloud

on:
 workflow_dispatch:
    inputs:
      spec:
        description: Run by cypress command line
        default: cypress/e2e/*
        
jobs:
  cypress-e2e--electron:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3.3.0
        
      - name: Cypress run
        uses: cypress-io/github-action@v5.3.1
        with:
          install-command: yarn install
          browser: electron
          record: true
          group: UI Electron
          spec: ${{ github.event.inputs.spec }}
        env:
          CYPRESS_RECORD_KEY: 1e6a9978-202a-4866-8104-3ae8471ffe04
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
